### PR TITLE
fix: Fix method BigmapDetection

### LINKED ISSUE #15: Error parsing BigMapIds
The README shows that to get all the bigmaps for a given contract one would do the following:

```
import (
	"github.com/trilitech/tzgo/micheline"
	"github.com/trilitech/tzgo/rpc"
	"github.com/trilitech/tzgo/tezos"
)

// we use the hic et nunc NFT market on mainnet as example
addr := tezos.MustParseAddress("KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9")

// init RPC client
c, _ := rpc.NewClient("https://rpc.tzstats.com", nil)

// fetch the contract's script and most recent storage
script, _ := c.GetContractScript(ctx, addr)

// bigmap pointers as []int64
ids := script.BigmapsById()

// bigmap pointers as named map[string]int64 (names from type annotations)
named := script.BigmapsByName()
```

The methods `BigmapsById`and `BigmapsByName` dont actually exist, however inspired by the above, the following works:

```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/trilitech/tzgo/rpc"
	"github.com/trilitech/tzgo/tezos"
)

func main() {
	// we use the hic et nunc NFT market on mainnet as example
	addr := tezos.MustParseAddress("<contract>")

	// init RPC client
	c, _ := rpc.NewClient("http://127.0.0.1:8732", nil)

	// fetch the contract's script and most recent storage
	script, _ := c.GetContractScript(context.Background(), addr)

	// bigmap pointers as []int64
	ids := script.Bigmaps()
	b, _ := json.Marshal(ids)

	fmt.Println(string(b))

}
```

And for most contracts this works, however sometimes, as for example the contract [KT1J1yVJEDkaYzJ7WuEomryEGWBNMGcUw1WA](https://better-call.dev/mainnet/KT1J1yVJEDkaYzJ7WuEomryEGWBNMGcUw1WA/storage) this returns a the correct bigmaps mixed into a lot of nonsense:

```
{"ledger":54254,"metadata":54253,"metadata_0":1,"metadata_1":2,
....
lots of garbage cleaned up for clarity ... 
....
,"metadata_998":999,"metadata_999":1000,"whitelist":54255}
```

Is there a different way to reliably fetch BigMap Ids?

### PR DESCRIPTION
**Pull request by huancheng-trili**
## What

Fix the method `BigmapDetection`.

I never really understood the logic of the original stack method. I decided to simply read the primitives following the michelson grammar. This requires all storage values to have the original primitive information, which is why the RPC code is updated.

## Why

Closes #15.

## Test

Added test cases. Note that one new test case is commented out because it breaks the `BigmapTypeDetection` method. This will be fixed in #17.

### CODE REVIEW

File: micheline/script.go [hunk 1]
```diff
@@ -157,11 +157,47 @@ func (s Script) Bigmaps() map[string]int64 {
 	return DetectBigmaps(s.Code.Storage, s.Storage)
 }
 
+// Flattens pair primitives. Basically the same as the UNPAIR michelson operation.
+// For instance, `pair (pair (pair 1 2) 3) 4` becomes `pair 1 2 3 4`. Other container
+// primitives like map and list remain untouched.
+func flatten(p Prim) []Prim {
```
Comment (huancheng-trili) [inline micheline/script.go:163]: This is needed because storage values are not always in the same shape as the type definitions in the storage code, specifically for pairs. Nested pair definitions can actually accept flattened storage values (see contract `KT1CSYNJ6dFcnsV4QJ6HnBFtdif8LJGPQiDM`,) so I flatten all pairs here just for consistency. In function `linkStorageTypeAndValue`, because pair values are assumed to be flattened, pair primitives continue to use the same value queue, unlike maps and lists that unfold the value on the spot and proceed recursively with the new unfolded value queue.
